---
title: "Reproducible Research: Peer Assessment 1: Scot J Matkovich"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, echo = TRUE}
fileURL = "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
destfile = "activity.zip"
if(!file.exists("activity.csv")) {
  download.file(fileURL, destfile)
  unzip(destfile)
}
activity <- read.csv(file="activity.csv")
activity_valid <- na.omit(activity)
```

## What is the mean and median total number of steps taken per day?
```{r, echo = TRUE}
library(dplyr)
steps <- activity_valid %>% group_by(date) %>% summarize(mean_steps = mean(steps), median_steps = median(steps))
hist(steps$mean_steps, main="mean steps per day", xlab="mean steps")
print(steps, n=nrow(steps))
```

## What is the average daily activity pattern?
```{r, echo = TRUE}
intervals <- activity_valid %>% group_by(interval) %>% summarize(mean_steps = mean(steps))
with(intervals, plot(interval, mean_steps, type="l"))
paste("Time interval with maximum mean steps is",intervals$interval[which(intervals$mean_steps == max(intervals$mean_steps))])
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
